sudo: required
dist: trusty

jobs:
  include:
    - stage: deploy
      name: "Publish Vorto-Dashboard to NPM"
      language: node_js
      node_js:
        - '10'
        
      cache:
        yarn: true
        directories:
          - ~/.cache
      
      before_install:
        - cd vorto-dashboard
      
      install:
        - echo "Installing dependencies"
        - yarn install
      
      after_success:
        - echo "Creating build"
        - npm run build
        - npm run dist
        
      before_deploy:
        - echo "Preparing for deploy to NPM" 
        - cd dist
        
      deploy:
        provider: npm
        skip_cleanup: true
        email: Alexander.Edelmann@bosch-si.com
        api_key:
          secure: $NPM_API_TOKEN
        on:
          tags: true
          branches:
            only:
              - master
  
